In [1]:
import numpy as np

data1 = [1,2,3,4,5]

array1 = np.array(data1)
array1


array([1, 2, 3, 4, 5])

In [2]:
data2 = [[1,2,3], [2,5,6]]
array2= np.array(data2)
array2

array([[1, 2, 3],
       [2, 5, 6]])

In [3]:
array2.dtype

dtype('int64')

In [4]:
array1.astype('str')

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [5]:
array1+1

array([2, 3, 4, 5, 6])

In [6]:
array1*array1

array([ 1,  4,  9, 16, 25])

In [7]:
array1*2

array([ 2,  4,  6,  8, 10])

In [8]:
array1


array([1, 2, 3, 4, 5])

In [9]:
array1[2]

3

In [10]:
array1[-2:]

array([4, 5])

In [11]:
array1[1]=0
array1

array([1, 0, 3, 4, 5])

In [12]:
array2

array([[1, 2, 3],
       [2, 5, 6]])

In [13]:
array2[0]

array([1, 2, 3])

In [14]:
array2[0][1]

2

In [23]:
from pandas import Series
X = Series(['a',2,'螃蟹'],[1,2,3])
X
X[3]


'螃蟹'

In [24]:
from pandas import Series
A = Series([1,2,3])
print(A)

0    1
1    2
2    3
dtype: int64


In [25]:
from pandas import Series
A = Series([1,2,3], index=[1,2,3])
print(A)

1    1
2    2
3    3
dtype: int64


In [26]:
from pandas import Series
A = Series([1,2,3],['A','B','C'])
print(A)

A    1
B    2
C    3
dtype: int64


In [29]:
from pandas import Series
A = Series([1,2,3],index=['A','B','C'])
print(A)

A    1
B    2
C    3
dtype: int64


In [32]:
from pandas import  Series
A = Series([14,26,31])
print(A)
print(A[1])
print(A[5])

0    14
1    26
2    31
dtype: int64
26


KeyError: 5

In [33]:
from pandas import  Series
A = Series([14,26,31], index=['first','second','third'])
print(A)
print(A['second'])

first     14
second    26
third     31
dtype: int64
26


In [41]:
from pandas import Series

#混合定义一个序列
x = Series(['a', True, 1], index=['first','second','third'])

#根据索引访问
x[1]
x['second']

#不能越界访问，会报错
# x[3]

#不能追加单个元素，但可以追加系列
# x.append('2')
#
# #追加一个系列
# n = Series(['2'])
# x.append(n)
#
# x = x.append(n)

2 in x.values

#切片
x[1:3]

#定位获取，这个方法经常用于随机采样
x[[0,2,1]]

#根据index删除
x.drop(0)
x.drop('first')

x.index[2]

x.drop(x.index[3])
x[2 != x.values]


KeyError: '[0] not found in axis'

In [44]:
from pandas import Series

A=Series([14,26,31],index=['first','second','third'])
print(A)
print(A['second'])

first     14
second    26
third     31
dtype: int64
26


In [52]:
from pandas import Series

#混合定义一个序列
x = Series(['a', True, 1], index=['first', 'second', 'third'])

#根据索引访问
x[1]
x['second']

#不能越界访问，会报错
# x[3]

#不能追加单个元素，但可以追加系列
# x.append('2')

#追加一个系列
n = Series(['2'])
x.append(n)

#需要使用一个变量来承载变化，即x.append(n)返回的是一个新序列
x = x.append(n)

#判断值是否存在，数字和逻辑型（True/False）是不需要加引号的
2 in x.values
'2' in x.values

#切片
x[1:3]

#定位获取，这个方法经常用于随机采样
x[0,2,1]

/var/folders/_w/tys32hhn1zl076008f10r1wr0000gn/T/ipykernel_1248/1268592759.py:18: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x.append(n)
/var/folders/_w/tys32hhn1zl076008f10r1wr0000gn/T/ipykernel_1248/1268592759.py:21: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x = x.append(n)


KeyError: 'key of type tuple not found and not a MultiIndex'

False

False