In [2]:
#一维数组
import  numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#元素类型要相同
import  numpy as np

arr = np.array([1,2,3,4.5,5,6,7,8])
arr

array([1. , 2. , 3. , 4.5, 5. , 6. , 7. , 8. ])

In [5]:
#多维数组

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,0], ndmin=2)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [8]:
#dtype参数
arr = np.array([1,2,3,4,5], dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

In [11]:
#dtype参数
arr = np.array([1,2,3,4,5], dtype='f8')
arr

array([1., 2., 3., 4., 5.])

In [12]:
#结构化数据类型
student = np.dtype([("name","S20"),("age","i4"),("marks","f4")])
arr = np.array( [("sunck", 18, 99.999), ("thomas", 19, 98.99)],dtype= student)
arr

array([(b'sunck', 18, 99.999), (b'thomas', 19, 98.99 )],
      dtype=[('name', 'S20'), ('age', '<i4'), ('marks', '<f4')])

In [13]:
arr = np.asarray([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
arr = np.asarray([(1,2,3),(4,5)], dtype=object)
arr

array([(1, 2, 3), (4, 5)], dtype=object)